In [2]:
import numpy as np

# -----------------------------
# Task 1 — Generate and Inspect
# -----------------------------
np.random.seed(42)

# 5 students × 4 subjects, scores 50–100
scores = np.random.randint(50, 101, (5, 4))
print("Scores:\n", scores)

# 1. Score of 3rd student in 2nd subject
score_3_2 = scores[2, 1]
print("\nScore of 3rd student, 2nd subject:", score_3_2)

# 2. Scores of last 2 students
last_two_students = scores[-2:]
print("\nLast 2 students' scores:\n", last_two_students)

# 3. First 3 students, subjects 2 and 3
subset_scores = np.sum(scores[:3, 1:3])
print("\nFirst 3 students (subjects 2 & 3):\n", subset_scores)



Scores:
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]]

Score of 3rd student, 2nd subject: 60

Last 2 students' scores:
 [[85 89 73 52]
 [71 51 73 93]]

First 3 students (subjects 2 & 3):
 420


In [3]:
# ------------------------------------
# Task 2 — Analyze with Broadcasting
# ------------------------------------

# 1. Column-wise mean (per subject)
col_mean = np.round(np.mean(scores, axis=0), 2)
print("\nColumn-wise mean:", col_mean)

# 2. Add curve with broadcasting
curve = np.array([5, 3, 7, 2])
curved_scores = scores + curve

# Cap scores at 100
curved_scores = np.clip(curved_scores, 0, 100)
print("\nCurved scores:\n", curved_scores)

# 3. Row-wise max (best subject per student)
row_max = np.max(curved_scores, axis=1)
print("\nRow-wise max of curved scores:", row_max)



Column-wise mean: [74.6 69.6 71.6 75.6]

Curved scores:
 [[93 81 71 94]
 [62 73 95 70]
 [77 63 67 75]
 [90 92 80 54]
 [76 54 80 95]]

Row-wise max of curved scores: [94 95 77 92 95]


In [25]:
# -------------------------------------------
# Task 3 — Normalize and Identify
# -------------------------------------------

# 1. Min-max normalize row-wise
row_min = curved_scores.min(axis=1, keepdims=True)
row_max_vals = curved_scores.max(axis=1, keepdims=True)
normalized = (curved_scores - row_min) / (row_max_vals - row_min)

print("\nNormalized scores:\n", normalized)

# 2. Identify the single highest value in normalized array
flat_index = np.argmax(normalized)
student_idx, subject_idx = np.unravel_index(flat_index, normalized.shape)

print("\nHighest normalized score at:")
print("Student index:", student_idx)
print("Subject index:", subject_idx)


# 3. Extract all curved scores > 90
above_90 = curved_scores[curved_scores > 90]
print("\nScores above 90:", above_90)


Normalized scores:
 [[0.95652174 0.43478261 0.         1.        ]
 [0.         0.33333333 1.         0.24242424]
 [1.         0.         0.28571429 0.85714286]
 [0.94736842 1.         0.68421053 0.        ]
 [0.53658537 0.         0.63414634 1.        ]]

Highest normalized score at:
Student index: 0
Subject index: 3

Scores above 90: [93 94 95 92 95]
